// Code generated by the Encore 1.50.4 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly music: music.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.music = new music.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    amapianorizeTrack as api_music_analyze_amapianorizeTrack,
    analyzeAudio as api_music_analyze_analyzeAudio,
    batchAnalyze as api_music_analyze_batchAnalyze,
    extractPatterns as api_music_analyze_extractPatterns,
    getAnalysisHistory as api_music_analyze_getAnalysisHistory,
    getBatchStatus as api_music_analyze_getBatchStatus,
    getUploadUrl as api_music_analyze_getUploadUrl
} from "~backend/music/analyze";
import {
    convertAudioFormat as api_music_audio_formats_convertAudioFormat,
    exportStems as api_music_audio_formats_exportStems,
    getAudioMetadata as api_music_audio_formats_getAudioMetadata,
    masterAudio as api_music_audio_formats_masterAudio
} from "~backend/music/audio-formats";
import {
    addComment as api_music_collaboration_addComment,
    collaborationSession as api_music_collaboration_collaborationSession,
    createCollaboration as api_music_collaboration_createCollaboration,
    createRemixChallenge as api_music_collaboration_createRemixChallenge,
    getCollaborationFeed as api_music_collaboration_getCollaborationFeed,
    joinCollaboration as api_music_collaboration_joinCollaboration,
    shareContent as api_music_collaboration_shareContent,
    submitRemix as api_music_collaboration_submitRemix
} from "~backend/music/collaboration";
import {
    generateDawElement as api_music_daw_generateDawElement,
    listProjects as api_music_daw_listProjects,
    loadProject as api_music_daw_loadProject,
    saveProject as api_music_daw_saveProject
} from "~backend/music/daw";
import {
    createLearningPath as api_music_education_createLearningPath,
    generateCulturalInsight as api_music_education_generateCulturalInsight,
    generateTutorial as api_music_education_generateTutorial,
    getCulturalInsights as api_music_education_getCulturalInsights,
    getEducationalContent as api_music_education_getEducationalContent,
    getLearningPaths as api_music_education_getLearningPaths,
    initializeBuiltinContent as api_music_education_initializeBuiltinContent
} from "~backend/music/education";
import {
    generateLoop as api_music_generate_generateLoop,
    generateTrack as api_music_generate_generateTrack,
    getGenerationHistory as api_music_generate_getGenerationHistory,
    getGenerationStats as api_music_generate_getGenerationStats
} from "~backend/music/generate";
import {
    getChordProgressions as api_music_patterns_getChordProgressions,
    getDrumPatterns as api_music_patterns_getDrumPatterns,
    listPatterns as api_music_patterns_listPatterns
} from "~backend/music/patterns";
import {
    createProjectSnapshot as api_music_realtime_collaboration_createProjectSnapshot,
    getActiveCollaborators as api_music_realtime_collaboration_getActiveCollaborators,
    getCollaborationStats as api_music_realtime_collaboration_getCollaborationStats,
    getProjectVersionHistory as api_music_realtime_collaboration_getProjectVersionHistory,
    liveCollaboration as api_music_realtime_collaboration_liveCollaboration
} from "~backend/music/realtime-collaboration";
import {
    createSample as api_music_samples_createSample,
    getSample as api_music_samples_getSample,
    getSampleStats as api_music_samples_getSampleStats,
    getSamplesByArtist as api_music_samples_getSamplesByArtist,
    listSamples as api_music_samples_listSamples,
    searchSamples as api_music_samples_searchSamples
} from "~backend/music/samples";

export namespace music {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addComment = this.addComment.bind(this)
            this.amapianorizeTrack = this.amapianorizeTrack.bind(this)
            this.analyzeAudio = this.analyzeAudio.bind(this)
            this.batchAnalyze = this.batchAnalyze.bind(this)
            this.collaborationSession = this.collaborationSession.bind(this)
            this.convertAudioFormat = this.convertAudioFormat.bind(this)
            this.createCollaboration = this.createCollaboration.bind(this)
            this.createLearningPath = this.createLearningPath.bind(this)
            this.createProjectSnapshot = this.createProjectSnapshot.bind(this)
            this.createRemixChallenge = this.createRemixChallenge.bind(this)
            this.createSample = this.createSample.bind(this)
            this.exportStems = this.exportStems.bind(this)
            this.extractPatterns = this.extractPatterns.bind(this)
            this.generateCulturalInsight = this.generateCulturalInsight.bind(this)
            this.generateDawElement = this.generateDawElement.bind(this)
            this.generateLoop = this.generateLoop.bind(this)
            this.generateTrack = this.generateTrack.bind(this)
            this.generateTutorial = this.generateTutorial.bind(this)
            this.getActiveCollaborators = this.getActiveCollaborators.bind(this)
            this.getAnalysisHistory = this.getAnalysisHistory.bind(this)
            this.getAudioMetadata = this.getAudioMetadata.bind(this)
            this.getBatchStatus = this.getBatchStatus.bind(this)
            this.getChordProgressions = this.getChordProgressions.bind(this)
            this.getCollaborationFeed = this.getCollaborationFeed.bind(this)
            this.getCollaborationStats = this.getCollaborationStats.bind(this)
            this.getCulturalInsights = this.getCulturalInsights.bind(this)
            this.getDrumPatterns = this.getDrumPatterns.bind(this)
            this.getEducationalContent = this.getEducationalContent.bind(this)
            this.getGenerationHistory = this.getGenerationHistory.bind(this)
            this.getGenerationStats = this.getGenerationStats.bind(this)
            this.getLearningPaths = this.getLearningPaths.bind(this)
            this.getProjectVersionHistory = this.getProjectVersionHistory.bind(this)
            this.getSample = this.getSample.bind(this)
            this.getSampleStats = this.getSampleStats.bind(this)
            this.getSamplesByArtist = this.getSamplesByArtist.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
            this.initializeBuiltinContent = this.initializeBuiltinContent.bind(this)
            this.joinCollaboration = this.joinCollaboration.bind(this)
            this.listPatterns = this.listPatterns.bind(this)
            this.listProjects = this.listProjects.bind(this)
            this.listSamples = this.listSamples.bind(this)
            this.liveCollaboration = this.liveCollaboration.bind(this)
            this.loadProject = this.loadProject.bind(this)
            this.masterAudio = this.masterAudio.bind(this)
            this.saveProject = this.saveProject.bind(this)
            this.searchSamples = this.searchSamples.bind(this)
            this.shareContent = this.shareContent.bind(this)
            this.submitRemix = this.submitRemix.bind(this)
        }

        /**
         * Adds a comment to a feed item
         */
        public async addComment(params: RequestType<typeof api_music_collaboration_addComment>): Promise<ResponseType<typeof api_music_collaboration_addComment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/comment`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_addComment>
        }

        /**
         * Enhanced amapianorize with cultural authenticity and quality metrics
         */
        public async amapianorizeTrack(params: RequestType<typeof api_music_analyze_amapianorizeTrack>): Promise<ResponseType<typeof api_music_analyze_amapianorizeTrack>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/amapianorize`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_amapianorizeTrack>
        }

        /**
         * Enhanced audio analysis with real AI processing
         */
        public async analyzeAudio(params: RequestType<typeof api_music_analyze_analyzeAudio>): Promise<ResponseType<typeof api_music_analyze_analyzeAudio>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/audio`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_analyzeAudio>
        }

        public async batchAnalyze(params: RequestType<typeof api_music_analyze_batchAnalyze>): Promise<ResponseType<typeof api_music_analyze_batchAnalyze>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/batch`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_batchAnalyze>
        }

        /**
         * Real-time collaboration session for a DAW project.
         */
        public async collaborationSession(params: RequestType<typeof api_music_collaboration_collaborationSession>): Promise<StreamInOut<StreamRequest<typeof api_music_collaboration_collaborationSession>, StreamResponse<typeof api_music_collaboration_collaborationSession>>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                projectId: String(params.projectId),
            })

            return await this.baseClient.createStreamInOut(`/daw/collaboration/session`, {query})
        }

        /**
         * API endpoints
         */
        public async convertAudioFormat(params: RequestType<typeof api_music_audio_formats_convertAudioFormat>): Promise<ResponseType<typeof api_music_audio_formats_convertAudioFormat>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audio/convert`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_audio_formats_convertAudioFormat>
        }

        /**
         * Creates a new collaboration space
         */
        public async createCollaboration(params: RequestType<typeof api_music_collaboration_createCollaboration>): Promise<ResponseType<typeof api_music_collaboration_createCollaboration>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_createCollaboration>
        }

        public async createLearningPath(params: RequestType<typeof api_music_education_createLearningPath>): Promise<ResponseType<typeof api_music_education_createLearningPath>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/learning-paths`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_createLearningPath>
        }

        /**
         * Create a project snapshot/version
         */
        public async createProjectSnapshot(params: RequestType<typeof api_music_realtime_collaboration_createProjectSnapshot>): Promise<void> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                createdBy:   params.createdBy,
                description: params.description,
            }

            await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.projectId)}/snapshot`, {method: "POST", body: JSON.stringify(body)})
        }

        /**
         * Creates a remix challenge
         */
        public async createRemixChallenge(params: RequestType<typeof api_music_collaboration_createRemixChallenge>): Promise<ResponseType<typeof api_music_collaboration_createRemixChallenge>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/remix-challenge`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_createRemixChallenge>
        }

        /**
         * Creates a new sample (for admin/content management)
         */
        public async createSample(params: RequestType<typeof api_music_samples_createSample>): Promise<ResponseType<typeof api_music_samples_createSample>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_createSample>
        }

        public async exportStems(params: RequestType<typeof api_music_audio_formats_exportStems>): Promise<ResponseType<typeof api_music_audio_formats_exportStems>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audio/export-stems`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_audio_formats_exportStems>
        }

        /**
         * Enhanced pattern extraction with expert-level analysis
         */
        public async extractPatterns(params: RequestType<typeof api_music_analyze_extractPatterns>): Promise<ResponseType<typeof api_music_analyze_extractPatterns>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/patterns`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_extractPatterns>
        }

        public async generateCulturalInsight(params: RequestType<typeof api_music_education_generateCulturalInsight>): Promise<ResponseType<typeof api_music_education_generateCulturalInsight>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/generate-insight`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_generateCulturalInsight>
        }

        /**
         * Generates a new track or clip for the DAW using AI.
         */
        public async generateDawElement(params: RequestType<typeof api_music_daw_generateDawElement>): Promise<ResponseType<typeof api_music_daw_generateDawElement>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/daw/ai-generate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_daw_generateDawElement>
        }

        /**
         * Enhanced loop generation with real AI processing
         */
        public async generateLoop(params: RequestType<typeof api_music_generate_generateLoop>): Promise<ResponseType<typeof api_music_generate_generateLoop>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/generate/loop`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_generate_generateLoop>
        }

        /**
         * Enhanced track generation with real AI processing
         */
        public async generateTrack(params: RequestType<typeof api_music_generate_generateTrack>): Promise<ResponseType<typeof api_music_generate_generateTrack>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/generate/track`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_generate_generateTrack>
        }

        /**
         * API endpoints
         */
        public async generateTutorial(params: RequestType<typeof api_music_education_generateTutorial>): Promise<ResponseType<typeof api_music_education_generateTutorial>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/generate-tutorial`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_generateTutorial>
        }

        /**
         * Get active collaborators for a project
         */
        public async getActiveCollaborators(params: { projectId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.projectId)}/active`, {method: "GET", body: undefined})
        }

        /**
         * Keep existing endpoints with enhanced error handling and validation
         */
        public async getAnalysisHistory(params: RequestType<typeof api_music_analyze_getAnalysisHistory>): Promise<ResponseType<typeof api_music_analyze_getAnalysisHistory>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                genre:      params.genre,
                limit:      params.limit === undefined ? undefined : String(params.limit),
                sortBy:     params.sortBy,
                sortOrder:  params.sortOrder === undefined ? undefined : String(params.sortOrder),
                sourceType: params.sourceType,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/history`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_getAnalysisHistory>
        }

        public async getAudioMetadata(params: RequestType<typeof api_music_audio_formats_getAudioMetadata>): Promise<ResponseType<typeof api_music_audio_formats_getAudioMetadata>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                url: params.url,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audio/metadata`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_audio_formats_getAudioMetadata>
        }

        public async getBatchStatus(params: { batchId: string }): Promise<ResponseType<typeof api_music_analyze_getBatchStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/batch/${encodeURIComponent(params.batchId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_getBatchStatus>
        }

        /**
         * Gets chord progressions specific to amapiano styles
         */
        public async getChordProgressions(params: RequestType<typeof api_music_patterns_getChordProgressions>): Promise<ResponseType<typeof api_music_patterns_getChordProgressions>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                complexity: params.complexity === undefined ? undefined : String(params.complexity),
                genre:      String(params.genre),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patterns/chords`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_patterns_getChordProgressions>
        }

        /**
         * Gets collaboration feed
         */
        public async getCollaborationFeed(params: RequestType<typeof api_music_collaboration_getCollaborationFeed>): Promise<ResponseType<typeof api_music_collaboration_getCollaborationFeed>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:    params.limit === undefined ? undefined : String(params.limit),
                offset:   params.offset === undefined ? undefined : String(params.offset),
                userName: params.userName,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.collaborationId)}/feed`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_getCollaborationFeed>
        }

        /**
         * Get collaboration statistics
         */
        public async getCollaborationStats(params: { projectId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.projectId)}/stats`, {method: "GET", body: undefined})
        }

        public async getCulturalInsights(params: RequestType<typeof api_music_education_getCulturalInsights>): Promise<ResponseType<typeof api_music_education_getCulturalInsights>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/cultural-insights`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_getCulturalInsights>
        }

        /**
         * Gets drum patterns specific to amapiano
         */
        public async getDrumPatterns(params: RequestType<typeof api_music_patterns_getDrumPatterns>): Promise<ResponseType<typeof api_music_patterns_getDrumPatterns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                genre: String(params.genre),
                style: params.style === undefined ? undefined : String(params.style),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patterns/drums`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_patterns_getDrumPatterns>
        }

        public async getEducationalContent(params: RequestType<typeof api_music_education_getEducationalContent>): Promise<ResponseType<typeof api_music_education_getEducationalContent>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category:   params.category,
                difficulty: params.difficulty,
                limit:      params.limit === undefined ? undefined : String(params.limit),
                offset:     params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/content`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_getEducationalContent>
        }

        /**
         * Keep existing endpoints with enhanced implementations
         */
        public async getGenerationHistory(params: RequestType<typeof api_music_generate_getGenerationHistory>): Promise<ResponseType<typeof api_music_generate_getGenerationHistory>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                filterBy:  params.filterBy === undefined ? undefined : String(params.filterBy),
                genre:     params.genre === undefined ? undefined : String(params.genre),
                limit:     params.limit === undefined ? undefined : String(params.limit),
                sortBy:    params.sortBy === undefined ? undefined : String(params.sortBy),
                sortOrder: params.sortOrder === undefined ? undefined : String(params.sortOrder),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/generate/history`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_generate_getGenerationHistory>
        }

        public async getGenerationStats(): Promise<ResponseType<typeof api_music_generate_getGenerationStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/generate/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_generate_getGenerationStats>
        }

        public async getLearningPaths(params: RequestType<typeof api_music_education_getLearningPaths>): Promise<ResponseType<typeof api_music_education_getLearningPaths>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                difficulty: params.difficulty,
                limit:      params.limit === undefined ? undefined : String(params.limit),
                offset:     params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/learning-paths`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_getLearningPaths>
        }

        /**
         * Project version history for synchronization
         */
        public async getProjectVersionHistory(params: { projectId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.projectId)}/versions`, {method: "GET", body: undefined})
        }

        /**
         * Retrieves a specific sample by ID
         */
        public async getSample(params: { id: number }): Promise<ResponseType<typeof api_music_samples_getSample>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_getSample>
        }

        /**
         * Gets statistics about the sample library
         */
        public async getSampleStats(): Promise<ResponseType<typeof api_music_samples_getSampleStats>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples/stats`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_getSampleStats>
        }

        /**
         * Gets samples in the style of specific amapiano artists
         */
        public async getSamplesByArtist(params: { artist: string }): Promise<ResponseType<typeof api_music_samples_getSamplesByArtist>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples/artist/${encodeURIComponent(params.artist)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_getSamplesByArtist>
        }

        /**
         * Enhanced upload URL generation with professional features
         */
        public async getUploadUrl(params: RequestType<typeof api_music_analyze_getUploadUrl>): Promise<ResponseType<typeof api_music_analyze_getUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_analyze_getUploadUrl>
        }

        /**
         * Built-in tutorial content
         */
        public async initializeBuiltinContent(): Promise<ResponseType<typeof api_music_education_initializeBuiltinContent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/education/initialize`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_education_initializeBuiltinContent>
        }

        /**
         * Joins an existing collaboration
         */
        public async joinCollaboration(params: RequestType<typeof api_music_collaboration_joinCollaboration>): Promise<ResponseType<typeof api_music_collaboration_joinCollaboration>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/join`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_joinCollaboration>
        }

        /**
         * Lists available amapiano patterns and progressions
         */
        public async listPatterns(params: RequestType<typeof api_music_patterns_listPatterns>): Promise<ResponseType<typeof api_music_patterns_listPatterns>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                bpm:          params.bpm === undefined ? undefined : String(params.bpm),
                category:     params.category === undefined ? undefined : String(params.category),
                genre:        params.genre === undefined ? undefined : String(params.genre),
                keySignature: params.keySignature,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/patterns`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_patterns_listPatterns>
        }

        /**
         * Lists all saved DAW projects.
         */
        public async listProjects(): Promise<ResponseType<typeof api_music_daw_listProjects>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/daw/projects`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_daw_listProjects>
        }

        /**
         * Lists available amapiano samples and loops
         */
        public async listSamples(params: RequestType<typeof api_music_samples_listSamples>): Promise<ResponseType<typeof api_music_samples_listSamples>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category === undefined ? undefined : String(params.category),
                genre:    params.genre === undefined ? undefined : String(params.genre),
                limit:    params.limit === undefined ? undefined : String(params.limit),
                tags:     params.tags?.map((v) => v),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_listSamples>
        }

        /**
         * Live collaboration stream endpoint - TODO: Fix streaming implementation
         */
        public async liveCollaboration(params: { projectId: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/collaboration/${encodeURIComponent(params.projectId)}/live`, {method: "POST", body: undefined})
        }

        /**
         * Loads a DAW project.
         */
        public async loadProject(params: { projectId: number }): Promise<ResponseType<typeof api_music_daw_loadProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/daw/projects/${encodeURIComponent(params.projectId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_daw_loadProject>
        }

        public async masterAudio(params: RequestType<typeof api_music_audio_formats_masterAudio>): Promise<ResponseType<typeof api_music_audio_formats_masterAudio>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/audio/master`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_audio_formats_masterAudio>
        }

        /**
         * Saves or updates a DAW project.
         */
        public async saveProject(params: RequestType<typeof api_music_daw_saveProject>): Promise<ResponseType<typeof api_music_daw_saveProject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/daw/projects`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_daw_saveProject>
        }

        /**
         * Searches samples by name, tags, or characteristics
         */
        public async searchSamples(params: RequestType<typeof api_music_samples_searchSamples>): Promise<ResponseType<typeof api_music_samples_searchSamples>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                category: params.category === undefined ? undefined : String(params.category),
                genre:    params.genre === undefined ? undefined : String(params.genre),
                query:    params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/samples/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_samples_searchSamples>
        }

        /**
         * Shares content in a collaboration
         */
        public async shareContent(params: RequestType<typeof api_music_collaboration_shareContent>): Promise<ResponseType<typeof api_music_collaboration_shareContent>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/share`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_shareContent>
        }

        /**
         * Submits a remix to a challenge
         */
        public async submitRemix(params: RequestType<typeof api_music_collaboration_submitRemix>): Promise<ResponseType<typeof api_music_collaboration_submitRemix>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/collaboration/remix-challenge/submit`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_music_collaboration_submitRemix>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.50.4)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
